language: node_js
node_js:
- "8"
cache: 
directories:
- node_modules
services:
  - postgresql
before_script:
  - npm install
  - psql -c 'create database test;' -U postgres
script:
- npm run test
notifications:
  email: false
